default: &default
  webhook_secret_key: pdl_ntfset_01hxm69xq1ewjcda88vf9pvbg5_REpembg9+HpKcVDUNQOkN6ydiO0jsfFE
  api_key: 766e215c49e0863f08c985e3abc4f6947789ac229a7ee419cb
  base_url: https://sandbox-api.paddle.com

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  webhook_secret_key: <%= ENV["PADDLE_WEBHOOK_SECRET_KEY"] %>
  api_key: <%= ENV["PADDLE_API_KEY"] %>
  base_url: https://api.paddle.com
